version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/pensioner-detail-44:2"
        LoadBalancerInfo:
          ContainerName: "pensioner-detail44"
          ContainerPort: "8000"
        PlatformVersion: "LATEST"